### ISSUE TITLE
Injecting/Mocking User

### ISSUE THREAD

**Issue by OneCyrus** [pamapa/oidc-client-ts#45]
For UI tests it would help a lot if we could inject a logged in user to oidc-client-ts. basically allow to inject an access token to skip the authentication flow.

**Comment by pamapa** [comment]
The library is storing the user with its access token in sessionStorage or localStorage. The key of that storage item is defined like
`oidc.user:${OIDC_AUTHORITY}:${OIDC_CLIENT_ID}`

You should be able to inject the access token there and make sure somewhere in the beginning of your production code you call 
`await userManager.getUser()`, which initiates the library with that data.

**Comment by OneCyrus** [comment]
ah now I got it working. the getUser was the trick. I always tried to get it to work with setting the sessionStorage and then calling the signinsilent.

thanks!

**Comment by barrymichaeldoyle** [comment]
Hmmm, I'm having the issue where my auth service is accessible via a VPN and the VPN is sometimes down so I want to bypass that during development. Is there a way to skip the signing redirect when I'm mocking my APIs?
